### ISSUE TITLE
Is this really a path?

### ISSUE THREAD

**Issue by bitemyapp** [steshaw/plt#14]
It seems more like a long and _very_ aspirational list.

**Comment by steshaw** [comment]
Yes, you're right. It started life as more of a path but grew into this grab bag.

**Comment by Zyst** [comment]
I would also like to see this trimmed/curated. Right now the list is frankly overwhelming, looks less like a path and more like just a regurgitated dump of (admittedly good) books on a ton of subjects.

A path is supposed to guide, in its current state this will just get you lost.

**Comment by MarisaKirisame** [comment]
I agree, but I think it will be bad to lost the books. Maybe a better idea is to create a new category that keep a short list of books that are very good and distinct? In this way you have a relatively easy way to know about plt in general, plus a further reading to tell you what to read, if you want to specialize in something.
Not strictly a path, but like, a map to plt enlightenment, with a path to get you basic knowledge real quick

**Comment by steshaw** [comment]
I'd like to highlight certain books (those that represent the "path"). For now, I previously added some advice from Wadler (just search for "wadler"). Also the books are supposed to be ordered in each section to help people find an appropriate book to start with and so on.

If you're wanting to learn type theory, I might recommend http://purelytheoretical.com/sywtltt.html

**Comment by steshaw** [comment]
Well this resource is what it is. It never promised to be a path, only to "help":

> Finding a path to enlightenment in Programming Language Theory can be a tough one, particularly for programming practitioners who didn't learn it at school. This resource is here to help.

I wish it was more of a path — if anyone has constructive criticism, please open an issue or pull request.
