### ISSUE TITLE
Add effect paper

### ISSUE THREAD

**Issue by MarisaKirisame** [steshaw/plt#31]
I think Effect is a nontrivial part of PL, and should be added.

The essence of algol, monads for functional programming, lambda the ultimate goto/assignment/imperative, dijkstra monad, lightweight monadic programming in ML, lazy functional state thread, denotational semantic (with effect)...

Somewhat related: should there also be imperative programming/axiomatic semantic paper/book? The craft of programming/A discipline of programming is both quite nice.

**Comment by MarisaKirisame** [comment]
A discipline of programming is mostly axiomatic semantic and stepwise refinement (sort of like program calculation, but imperative).

The craft of programming is (IMO) a less radical, and easier to read version of ADOP.

**Comment by MarisaKirisame** [comment]
I can do a pull request soon.

**Comment by suhailshergill** [comment]
Unsure if relevant, but Oleg's "having an effect" webpage has some excellent references. 
Shameless plug: extensible-effects is an implementation of those ideas in Haskell

**Comment by MarisaKirisame** [comment]
I am currently reading them, lol

**Comment by MarisaKirisame** [comment]
Freer Monads, More Extensible Effects
listing papers as I read along...

**Comment by MarisaKirisame** [comment]
https://github.com/yallop/effects-bibliography

**Comment by steshaw** [comment]
Fixed via [adding an "Effects Systems" subtopic](https://github.com/steshaw/plt/commit/a73906b06127981ca01c2a2ec751e1290910f2e2). Let me know if any other resources should be added to it. I imagine most of the papers should be added directly to @yallop's effects bibliography.
