### ISSUE TITLE
Add Program analysis

### ISSUE THREAD

**Issue by MarisaKirisame** [steshaw/plt#47]
principle of program analysis
https://cs.au.dk/~amoeller/spa/spa.pdf

**Comment by steshaw** [comment]
Nice book! I've added it to "Compiler Construction" for want of a better location.

**Comment by MarisaKirisame** [comment]
@steshaw hmm... program analysis do get used in compiler, but ppl also use it for bug finding. maybe it deserve it's own category?

**Comment by steshaw** [comment]
I know what you mean but I don't have a program analysis category right now ...
