### ISSUE TITLE
Link for "PLT Texts Online - Frank Atanassow" looks broken

### ISSUE THREAD

**Issue by gihyeonsung** [steshaw/plt#50]
I wanted to submit PR for the broken link. But I couldn't because I've never seen the contents of the broken link.

Can anyone fix the link?

**Comment by steshaw** [comment]
I found it in the Wayback Machine

https://web.archive.org/web/20141002195305/http://www.cs.uu.nl:80/wiki/Techno/ProgrammingLanguageTheoryTextsOnline
