### ISSUE TITLE
I have some useful links on topics related to programming languages..

### ISSUE THREAD

**Issue by Francesco601** [steshaw/plt#59]
[https://plato.stanford.edu/index.html](url)

**Comment by Francesco601** [comment]
I have a few others, Let me know if you are interested

**Comment by steshaw** [comment]
I don't want to add a general link to the Stanford Encyclopedia of Philosophy, but one article I like there is [Type Theory by Thierry Coquand](https://plato.stanford.edu/entries/type-theory/). I thought it was in the collection already, but it doesn't seem to be. Feel free to raise a PR to add that one.

If you have other good resources, please share!

**Comment by Francesco601** [comment]
Oh, I'm sorry. I gave the wrong link for some reason..[https://plato.stanford.edu/entries/lambda-calculus/](url)
