### ISSUE TITLE
Hmm...I can't seem to do a pull request for some reason. New to Github....

### ISSUE THREAD

**Issue by Francesco601** [steshaw/plt#60]
I gave the wrong url in my first comment. Here's the one you linked to. [https://plato.stanford.edu/entries/type-theory/](url)
And here is the original one that I meant to post [https://plato.stanford.edu/entries/lambda-calculus/](url)

**Comment by markgreene74** [comment]
> I can't seem to do a pull request for some reason

@Francesco601 have a look at this page: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by steshaw** [comment]
It looks like you're all sorted. Just merged you first PR https://github.com/steshaw/plt/pull/62.
