### ISSUE TITLE
Link text too slim in Chrome and IE

### ISSUE THREAD

**Issue by drasive** [steshaw/plt#8]
The link text on [http://steshaw.org/plt/](http://steshaw.org/plt/) gets rendered really slim and is hard to read in Chrome  and IE . It is fine in Firefox.

Chrome (v43.0.2357.130 m):
![image](https://cloud.githubusercontent.com/assets/8427113/8383372/e915b3ca-1c39-11e5-9e08-ef6ac37bb54e.png)
Internet Explorer (11.0.9600.17842):
![image](https://cloud.githubusercontent.com/assets/8427113/8383346/aab93110-1c39-11e5-8c18-efe2d58b5bc5.png)
Firefox (v37.0.2):
![image](https://cloud.githubusercontent.com/assets/8427113/8383348/b4456df2-1c39-11e5-839e-d68a36acb88e.png)

**Comment by steshaw** [comment]
Hi @drasive, I'm not a web designer but I've tweaking the CSS. Let me know what you think.

https://www.browserstack.com/screenshots/1eaa18899838cea7c2c55cd9e806903a9ac5fe71
